export const state = [
    {label: "15 Minutes Prep", time: 15, warn: false},
    {label: "1st Affirmative", time: 240, warn: true},
    {label: "1 Minute Prep", time: 60, warn: false},
    {label: "1st Negative", time: 240, warn: true},
    {label: "1 Minute Prep", time: 60, warn: false},
    {label: "2nd Affirmative", time: 240, warn: true},
    {label: "1 Minute Prep", time: 60, warn: false},
    {label: "2nd Negative", time: 240, warn: true},
    {label: "1 Minute Prep", time: 60, warn: false},
    {label: "3rd Affirmative", time: 240, warn: true},
    {label: "1 Minute Prep", time: 60, warn: false},
    {label: "3rd Negative", time: 240, warn: true},
    {label: "Feedback Prep", time: 90, warn: false},
    {label: "Neg Team Feedback", time: 90, warn: false},
    {label: "Aff Team Feedback", time: 90, warn: false},
]